server {
    listen 80;
    server_name megalomaniac.dev.local;
    root /var/www/megalomaniac/public;
    index index.php;
    location / { try_files $uri $uri/ /index.php?$query_string; }
    location ~ \.php$ {
        fastcgi_pass dev-megalomaniac:8070;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_read_timeout 600s;
        fastcgi_send_timeout 600s;
        fastcgi_buffering off;
    }
}
